SET SERVEROUTPUT ON;
SET VERIFY OFF;

ACCEPT X PROMPT "ENTER COMPANY NAME: "
ACCEPT Y PROMPT "ENTER COMPANY ADDRESS: "
ACCEPT Z PROMPT "ENTER COMPANY Email: "
ACCEPT X1 PROMPT "ENTER COMPANY CONTACT NUMBER: "
ACCEPT Y2 PROMPT "ENTER JOBS REQUIREMENT : "
ACCEPT Z2 PROMPT "ENTER SALARY: "
ACCEPT X2 PROMPT "ENTER AVAILABLE POSITION: "


DECLARE
	A VARCHAR2(20);
	B VARCHAR2(20);
	C VARCHAR2(20);
	D VARCHAR2(20);
	E VARCHAR2(20);
	F VARCHAR2(20);
	G VARCHAR2(20);

BEGIN
	A:='&X';
	B:='&Y';
	C:='&Z';
	D:='&X1';
	E:='&Y2';
	F:='&Z2';
	G:='&X2';
	
	insert into Employer_approval@server1 values(A,B,C,D,E,F,G);
	
	
	
	
	
END;	
/
commit;





